In [1]:
# !pip install pandas

In [1]:
import os
import pandas as pd

In [2]:
cwd = os.getcwd() # dirname(abspath(__file__))
BASE_DIR = os.path.dirname(cwd)
DATA_DIR = os.path.join(BASE_DIR, 'data')
CACHE_DIR = os.path.join(BASE_DIR, 'cache')
os.makedirs(CACHE_DIR, exist_ok=True)

In [3]:
for filename in os.listdir(DATA_DIR):
    print(filename)

2020.csv
2021.csv
2023.csv
2022.csv
2026.csv
2025.csv
2024.csv

In [5]:
df = pd.read_csv(os.path.join(DATA_DIR, '2020.csv'))
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008",10.6%,"$419,614,312",89.4%
1,2,The Eight Hundred,"$461,421,559","$372,755",<0.1%,"$461,048,804",99.9%
2,3,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%
3,4,"My People, My Homeland","$422,390,820",-,-,"$422,390,820",100%
4,5,Tenet,"$365,304,105","$58,504,105",16%,"$306,800,000",84%

In [6]:
df['Year'] = 2010

In [7]:
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,Year
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008",10.6%,"$419,614,312",89.4%,2010
1,2,The Eight Hundred,"$461,421,559","$372,755",<0.1%,"$461,048,804",99.9%,2010
2,3,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%,2010
3,4,"My People, My Homeland","$422,390,820",-,-,"$422,390,820",100%,2010
4,5,Tenet,"$365,304,105","$58,504,105",16%,"$306,800,000",84%,2010

In [8]:
df['Start Year'] = df['Year'] * 55

In [9]:
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,Year,Start Year
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008",10.6%,"$419,614,312",89.4%,2010,110550
1,2,The Eight Hundred,"$461,421,559","$372,755",<0.1%,"$461,048,804",99.9%,2010,110550
2,3,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%,2010,110550
3,4,"My People, My Homeland","$422,390,820",-,-,"$422,390,820",100%,2010,110550
4,5,Tenet,"$365,304,105","$58,504,105",16%,"$306,800,000",84%,2010,110550

In [10]:

my_dataframes = []
csv_files = [x for x in os.listdir(DATA_DIR) if x.endswith(".csv")]

for filename in csv_files:
    print(filename)
    year = filename.replace(".csv", "")
    csv_path = os.path.join(DATA_DIR, filename)
    this_df = pd.read_csv(csv_path)
    this_df['filename'] = filename
    this_df['year'] = year
    print(this_df.head(n=1))
    my_dataframes.append(this_df)

2020.csv
   Rank                                      Release Group     Worldwide  \
0     1  Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...  $469,119,320

      Domestic      %       Foreign    %.1  filename  year
0  $49,505,008  10.6%  $419,614,312  89.4%  2020.csv  2020
2021.csv
   Rank            Release Group       Worldwide      Domestic      %  \
0     1  Spider-Man: No Way Home  $1,910,982,770  $804,793,477  42.1%

          Foreign    %.1  filename  year
0  $1,106,189,293  57.9%  2021.csv  2021
2023.csv
   Rank Release Group       Worldwide      Domestic    %       Foreign  %.1  \
0     1        Barbie  $1,447,138,421  $636,238,421  44%  $810,900,000  56%

   filename  year
0  2023.csv  2023
2022.csv
   Rank             Release Group       Worldwide      Domestic      %  \
0     1  Avatar: The Way of Water  $2,320,631,329  $684,075,767  29.5%

          Foreign    %.1  filename  year
0  $1,636,555,562  70.5%  2022.csv  2022
2026.csv
   Rank Release Group     Worldwide    Domestic     %       Foreign    %.1  \
0     1     Pegasus 3  $599,266,655  $1,374,946  0.2%  $597,891,709  99.8%

   filename  year
0  2026.csv  2026
2025.csv
   Rank Release Group       Worldwide     Domestic   %         Foreign  %.1  \
0     1      Ne Zha 2  $2,260,176,370  $23,308,176  1%  $2,236,868,194  99%

   filename  year
0  2025.csv  2025
2024.csv
   Rank Release Group       Worldwide      Domestic      %         Foreign  \
0     1  Inside Out 2  $1,698,863,816  $652,980,194  38.4%  $1,045,883,622

     %.1  filename  year
0  61.6%  2024.csv  2024

In [11]:
my_entire_dataframe = pd.concat(my_dataframes)

In [12]:
my_entire_dataframe.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008",10.6%,"$419,614,312",89.4%,2020.csv,2020
1,2,The Eight Hundred,"$461,421,559","$372,755",<0.1%,"$461,048,804",99.9%,2020.csv,2020
2,3,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%,2020.csv,2020
3,4,"My People, My Homeland","$422,390,820",-,-,"$422,390,820",100%,2020.csv,2020
4,5,Tenet,"$365,304,105","$58,504,105",16%,"$306,800,000",84%,2020.csv,2020

In [13]:
my_entire_dataframe.tail()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
195,196,Uma Musume: Pretty Derby - Beginning of a New Era,"$9,826,205","$1,274,568",13%,"$8,551,637",87%,2024.csv,2024
196,197,Letters to Santa 6,"$9,782,064",-,-,"$9,782,064",100%,2024.csv,2024
197,198,Buffalo Kids,"$9,697,110","$214,534",2.2%,"$9,482,576",97.8%,2024.csv,2024
198,199,The Chosen: S4 Episodes 4-6,"$9,482,744","$9,482,744",100%,-,-,2024.csv,2024
199,200,A Smile Doesn't Lie,"$9,211,570",-,-,"$9,211,570",100%,2024.csv,2024

In [14]:
dataset = os.path.join(CACHE_DIR, 'movies-box-office-dataset.csv')
my_entire_dataframe.to_csv(dataset, index=False)