In [12]:
import os
import pandas as pd

In [31]:
#Current working directory

cwd = os.getcwd() # dirname (abspath(file))
BASE_DIR = os.path.dirname(cwd)
DATA_DIR = os.path.join(BASE_DIR, 'data')
CACHE_DIR = os.path.join (BASE_DIR,'cache')
os.makedirs(CACHE_DIR, exist_ok=True)

In [32]:
for filename in os.listdir(DATA_DIR) :
    print(filename)

2020.csv
2021.csv
2023.csv
2022.csv
2026.csv
2025.csv
2024.csv

In [33]:
df = pd.read_csv(os.path.join(DATA_DIR, "2026.csv"))
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,Pegasus 3,"$599,266,655","$1,374,946",0.2%,"$597,891,709",99.8%
1,2,Wuthering Heights,"$226,563,318","$82,163,318",36.3%,"$144,400,000",63.7%
2,3,Scream 7,"$177,977,862","$107,577,862",60.4%,"$70,400,000",39.6%
3,4,Hoppers,"$168,677,616","$90,618,975",53.7%,"$78,058,641",46.3%
4,5,Blades of the Guardians,"$168,462,054","$1,562,054",0.9%,"$166,900,000",99.1%

In [34]:
df["my approval"] = "Given"
df["year"] = "2021"
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,my approval,year
0,1,Pegasus 3,"$599,266,655","$1,374,946",0.2%,"$597,891,709",99.8%,Given,2021
1,2,Wuthering Heights,"$226,563,318","$82,163,318",36.3%,"$144,400,000",63.7%,Given,2021
2,3,Scream 7,"$177,977,862","$107,577,862",60.4%,"$70,400,000",39.6%,Given,2021
3,4,Hoppers,"$168,677,616","$90,618,975",53.7%,"$78,058,641",46.3%,Given,2021
4,5,Blades of the Guardians,"$168,462,054","$1,562,054",0.9%,"$166,900,000",99.1%,Given,2021

In [35]:
my_entire_dataframe = pd.DataFrame()
csv_files = [x for x in os.listdir(DATA_DIR) if x.endswith(".csv") ]
my_dataframe = []

for filename in csv_files:
    print (filename, "\n")
    year = filename.replace(".csv", "")
    csv_path = os.path.join(DATA_DIR, filename)
    this_df = pd.read_csv(csv_path)
    this_df['filename'] = filename
    this_df['year'] = year
    print(this_df.head(n=1), "\n\n\n")
    my_dataframe.append(this_df)

2020.csv

   Rank                                      Release Group     Worldwide  \
0     1  Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...  $469,119,320

      Domestic      %       Foreign    %.1  filename  year
0  $49,505,008  10.6%  $419,614,312  89.4%  2020.csv  2020



2021.csv

   Rank            Release Group       Worldwide      Domestic      %  \
0     1  Spider-Man: No Way Home  $1,910,982,770  $804,793,477  42.1%

          Foreign    %.1  filename  year
0  $1,106,189,293  57.9%  2021.csv  2021



2023.csv

   Rank Release Group       Worldwide      Domestic    %       Foreign  %.1  \
0     1        Barbie  $1,447,138,421  $636,238,421  44%  $810,900,000  56%

   filename  year
0  2023.csv  2023



2022.csv

   Rank             Release Group       Worldwide      Domestic      %  \
0     1  Avatar: The Way of Water  $2,320,631,329  $684,075,767  29.5%

          Foreign    %.1  filename  year
0  $1,636,555,562  70.5%  2022.csv  2022



2026.csv

   Rank Release Group     Worldwide    Domestic     %       Foreign    %.1  \
0     1     Pegasus 3  $599,266,655  $1,374,946  0.2%  $597,891,709  99.8%

   filename  year
0  2026.csv  2026



2025.csv

   Rank Release Group       Worldwide     Domestic   %         Foreign  %.1  \
0     1      Ne Zha 2  $2,260,176,370  $23,308,176  1%  $2,236,868,194  99%

   filename  year
0  2025.csv  2025



2024.csv

   Rank Release Group       Worldwide      Domestic      %         Foreign  \
0     1  Inside Out 2  $1,698,863,816  $652,980,194  38.4%  $1,045,883,622

     %.1  filename  year
0  61.6%  2024.csv  2024

In [36]:
my_dataframe

[     Rank                                      Release Group     Worldwide  \
 0       1  Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...  $469,119,320
 1       2                                  The Eight Hundred  $461,421,559
 2       3                                  Bad Boys for Life  $426,505,244
 3       4                             My People, My Homeland  $422,390,820
 4       5                                              Tenet  $365,304,105
 ..    ...                                                ...           ...
 195   196                          The Broken Hearts Gallery    $4,781,389
 196   197                         Gladiator 20th Anniversary    $4,780,585
 197   198                                           Intruder    $4,751,103
 198   199                      Paw Patrol: Jet to the Rescue    $4,693,664
 199   200                                       Granny Nanny    $4,654,655

          Domestic      %       Foreign    %.1  filename  year
 0     $49,505,008  10.6%  $419,614,312  89.4%  2020.csv  2020
 1        $372,755  <0.1%  $461,048,804  99.9%  2020.csv  2020
 2    $206,305,244  48.4%  $220,200,000  51.6%  2020.csv  2020
 3               -      -  $422,390,820   100%  2020.csv  2020
 4     $58,504,105    16%  $306,800,000    84%  2020.csv  2020
 ..            ...    ...           ...    ...       ...   ...
 195    $4,067,442  85.1%      $713,947  14.9%  2020.csv  2020
 196             -      -    $4,780,585   100%  2020.csv  2020
 197             -      -    $4,751,103   100%  2020.csv  2020
 198             -      -    $4,693,664   100%  2020.csv  2020
 199          $432  <0.1%    $4,654,223   100%  2020.csv  2020

 [200 rows x 9 columns],
      Rank                Release Group       Worldwide      Domestic      %  \
 0       1      Spider-Man: No Way Home  $1,910,982,770  $804,793,477  42.1%
 1       2  The Battle at Lake Changjin    $902,548,476      $342,411  <0.1%
 2       3                      Hi, Mom    $822,009,764             -      -
 3       4               No Time to Die    $774,153,007  $160,891,007  20.8%
 4       5            F9: The Fast Saga    $726,229,501  $173,005,945  23.8%
 ..    ...                          ...             ...           ...    ...
 195   196              The Mauritanian      $7,527,030      $836,536  11.1%
 196   197                 The Ice Road      $7,502,846             -      -
 197   198  Judas and the Black Messiah      $7,478,009    $5,478,009  73.3%
 198   199  Love Letter 2021 Re-release      $7,400,000             -      -
 199   200            Signal: The Movie      $7,388,603             -      -

             Foreign    %.1  filename  year
 0    $1,106,189,293  57.9%  2021.csv  2021
 1      $902,206,065   100%  2021.csv  2021
 2      $822,009,764   100%  2021.csv  2021
 3      $613,262,000  79.2%  2021.csv  2021
 4      $553,223,556  76.2%  2021.csv  2021
 ..              ...    ...       ...   ...
 195      $6,690,494  88.9%  2021.csv  2021
 196      $7,502,846   100%  2021.csv  2021
 197      $2,000,000  26.7%  2021.csv  2021
 198      $7,400,000   100%  2021.csv  2021
 199      $7,388,603   100%  2021.csv  2021

 [200 rows x 9 columns],
      Rank                       Release Group       Worldwide      Domestic  \
 0       1                              Barbie  $1,447,138,421  $636,238,421
 1       2         The Super Mario Bros. Movie  $1,360,879,735  $574,934,330
 2       3                         Oppenheimer    $975,811,333  $330,078,895
 3       4      Guardians of the Galaxy Vol. 3    $845,555,777  $358,995,815
 4       5                              Fast X    $704,875,015  $146,126,015
 ..    ...                                 ...             ...           ...
 195   196                    Sun and Concrete     $10,120,340             -
 196   197                              Cobweb     $10,091,821             -
 197   198                        The Peasants     $10,067,544      $155,188
 198   199  Talk to Her Undated France Release      $9,550,733             -
 199   200                            Kandahar      $9,387,311    $4,813,132

          %       Foreign    %.1  filename  year
 0      44%  $810,900,000    56%  2023.csv  2023
 1    42.2%  $785,945,405  57.8%  2023.csv  2023
 2    33.8%  $645,732,438  66.2%  2023.csv  2023
 3    42.5%  $486,559,962  57.5%  2023.csv  2023
 4    20.7%  $558,749,000  79.3%  2023.csv  2023
 ..     ...           ...    ...       ...   ...
 195      -   $10,120,340   100%  2023.csv  2023
 196      -   $10,091,821   100%  2023.csv  2023
 197   1.5%    $9,912,356  98.5%  2023.csv  2023
 198      -    $9,549,770   100%  2023.csv  2023
 199  51.3%    $4,574,179  48.7%  2023.csv  2023

 [200 rows x 9 columns],
      Rank                                Release Group       Worldwide  \
 0       1                     Avatar: The Way of Water  $2,320,631,329
 1       2                            Top Gun: Maverick  $1,495,696,292
 2       3                     Jurassic World: Dominion  $1,001,978,080
 3       4  Doctor Strange in the Multiverse of Madness    $955,775,804
 4       5                     Minions: The Rise of Gru    $940,482,695
 ..    ...                                          ...             ...
 195   196                                  The New Toy      $7,295,051
 196   197                                      Decibel      $7,212,471
 197   198                       The Kids Are Alright 2      $7,187,470
 198   199                        My Fairy Troublemaker      $7,178,001
 199   200    Mobile Suit Gundam: Cucuruz Doan's Island      $7,006,640

          Domestic      %         Foreign    %.1  filename  year
 0    $684,075,767  29.5%  $1,636,555,562  70.5%  2022.csv  2022
 1    $718,732,821  48.1%    $776,963,471  51.9%  2022.csv  2022
 2    $376,851,080  37.6%    $625,127,000  62.4%  2022.csv  2022
 3    $411,331,607    43%    $544,444,197    57%  2022.csv  2022
 4    $370,549,695  39.4%    $569,933,000  60.6%  2022.csv  2022
 ..            ...    ...             ...    ...       ...   ...
 195             -      -      $7,295,051   100%  2022.csv  2022
 196       $60,579   0.8%      $7,151,892  99.2%  2022.csv  2022
 197             -      -      $7,187,470   100%  2022.csv  2022
 198             -      -      $7,178,001   100%  2022.csv  2022
 199             -      -      $7,006,640   100%  2022.csv  2022

 [200 rows x 9 columns],
      Rank                                      Release Group     Worldwide  \
 0       1                                          Pegasus 3  $599,266,655
 1       2                                  Wuthering Heights  $226,563,318
 2       3                                           Scream 7  $177,977,862
 3       4                                            Hoppers  $168,677,616
 4       5                            Blades of the Guardians  $168,462,054
 ..    ...                                                ...           ...
 195   196                            Tripping With My Family      $506,909
 196   197                                 My Father's Shadow      $480,346
 197   198                             The Mortuary Assistant      $470,102
 198   199  Fukuyama Masaharu raivu firumu@ Nagasaki gekko...      $469,150
 199   200                                        Prakambanam      $460,175

          Domestic      %       Foreign    %.1  filename  year
 0      $1,374,946   0.2%  $597,891,709  99.8%  2026.csv  2026
 1     $82,163,318  36.3%  $144,400,000  63.7%  2026.csv  2026
 2    $107,577,862  60.4%   $70,400,000  39.6%  2026.csv  2026
 3     $90,618,975  53.7%   $78,058,641  46.3%  2026.csv  2026
 4      $1,562,054   0.9%  $166,900,000  99.1%  2026.csv  2026
 ..            ...    ...           ...    ...       ...   ...
 195             -      -      $506,909   100%  2026.csv  2026
 196      $105,898    22%      $374,448    78%  2026.csv  2026
 197      $454,776  96.7%       $15,326   3.3%  2026.csv  2026
 198             -      -      $469,150   100%  2026.csv  2026
 199             -      -      $460,175   100%  2026.csv  2026

 [200 rows x 9 columns],
      Rank                        Release Group       Worldwide      Domestic  \
 0       1                             Ne Zha 2  $2,260,176,370   $23,308,176
 1       2                           Zootopia 2  $1,866,361,674  $427,843,884
 2       3                 Avatar: Fire and Ash  $1,485,065,497  $403,405,617
 3       4                        Lilo & Stitch  $1,038,027,526  $423,778,855
 4       5                    A Minecraft Movie    $961,187,780  $424,087,780
 ..    ...                                  ...             ...           ...
 195   196                                Grace     $10,048,372      $132,311
 196   197                Sisu: Road to Revenge      $9,811,703    $4,544,481
 197   198                      Chasse gardée 2      $9,788,446             -
 198   199  Detective Kien: The Headless Horror      $9,768,694             -
 199   200                    Is This Thing On?      $9,746,540    $6,185,385

          %         Foreign    %.1  filename  year
 0       1%  $2,236,868,194    99%  2025.csv  2025
 1    22.9%  $1,438,517,790  77.1%  2025.csv  2025
 2    27.2%  $1,081,659,880  72.8%  2025.csv  2025
 3    40.8%    $614,248,671  59.2%  2025.csv  2025
 4    44.1%    $537,100,000  55.9%  2025.csv  2025
 ..     ...             ...    ...       ...   ...
 195   1.3%      $9,916,061  98.7%  2025.csv  2025
 196  46.3%      $5,267,222  53.7%  2025.csv  2025
 197      -      $9,788,446   100%  2025.csv  2025
 198      -      $9,768,694   100%  2025.csv  2025
 199  63.5%      $3,561,155  36.5%  2025.csv  2025

 [200 rows x 9 columns],
      Rank                                      Release Group       Worldwide  \
 0       1                                       Inside Out 2  $1,698,863,816
 1       2                               Deadpool & Wolverine  $1,338,073,645
 2       3                                            Moana 2  $1,059,242,164
 3       4                                    Despicable Me 4    $972,021,410
 4       5                                             Wicked    $758,790,057
 ..    ...                                                ...             ...
 195   196  Uma Musume: Pretty Derby - Beginning of a New Era      $9,826,205
 196   197                                 Letters to Santa 6      $9,782,064
 197   198                                       Buffalo Kids      $9,697,110
 198   199                        The Chosen: S4 Episodes 4-6      $9,482,744
 199   200                                A Smile Doesn't Lie      $9,211,570

          Domestic      %         Foreign    %.1  filename  year
 0    $652,980,194  38.4%  $1,045,883,622  61.6%  2024.csv  2024
 1    $636,745,858  47.6%    $701,327,787  52.4%  2024.csv  2024
 2    $460,405,297  43.5%    $598,836,867  56.5%  2024.csv  2024
 3    $361,004,205  37.1%    $611,017,205  62.9%  2024.csv  2024
 4    $474,983,975  62.6%    $283,806,082  37.4%  2024.csv  2024
 ..            ...    ...             ...    ...       ...   ...
 195    $1,274,568    13%      $8,551,637    87%  2024.csv  2024
 196             -      -      $9,782,064   100%  2024.csv  2024
 197      $214,534   2.2%      $9,482,576  97.8%  2024.csv  2024
 198    $9,482,744   100%               -      -  2024.csv  2024
 199             -      -      $9,211,570   100%  2024.csv  2024

 [200 rows x 9 columns]]

In [38]:
my_entire_dataframe = pd.concat(my_dataframe) # to combine many dataframes
my_entire_dataframe.head() , my_entire_dataframe.tail()

(   Rank                                      Release Group     Worldwide  \
 0     1  Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...  $469,119,320
 1     2                                  The Eight Hundred  $461,421,559
 2     3                                  Bad Boys for Life  $426,505,244
 3     4                             My People, My Homeland  $422,390,820
 4     5                                              Tenet  $365,304,105

        Domestic      %       Foreign    %.1  filename  year
 0   $49,505,008  10.6%  $419,614,312  89.4%  2020.csv  2020
 1      $372,755  <0.1%  $461,048,804  99.9%  2020.csv  2020
 2  $206,305,244  48.4%  $220,200,000  51.6%  2020.csv  2020
 3             -      -  $422,390,820   100%  2020.csv  2020
 4   $58,504,105    16%  $306,800,000    84%  2020.csv  2020  ,
      Rank                                      Release Group   Worldwide  \
 195   196  Uma Musume: Pretty Derby - Beginning of a New Era  $9,826,205
 196   197                                 Letters to Santa 6  $9,782,064
 197   198                                       Buffalo Kids  $9,697,110
 198   199                        The Chosen: S4 Episodes 4-6  $9,482,744
 199   200                                A Smile Doesn't Lie  $9,211,570

        Domestic     %     Foreign    %.1  filename  year
 195  $1,274,568   13%  $8,551,637    87%  2024.csv  2024
 196           -     -  $9,782,064   100%  2024.csv  2024
 197    $214,534  2.2%  $9,482,576  97.8%  2024.csv  2024
 198  $9,482,744  100%           -      -  2024.csv  2024
 199           -     -  $9,211,570   100%  2024.csv  2024  )

In [40]:
dataset = os.path.join(CACHE_DIR,'movies-box-office-dataset.csv')
my_entire_dataframe.to_csv(dataset, index = False)