In [2]:
import os
import pandas as pd

In [27]:
#Current working directory

cwd = os.getcwd() # dirname (abspath(file))
BASE_DIR = os.path.dirname(cwd)
DATA_DIR = os.path.join(BASE_DIR, 'data')
CACHE_DIR = os.path.join(BASE_DIR,'cache')
working_file = os.path.join(CACHE_DIR, 'movies-box-office-dataset.csv')
output_file = os.path.join(CACHE_DIR, 'movies-box-office-dataset-cleaned.csv')

In [4]:
df = pd.read_csv(working_file)
df.head(n=1200)

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008",10.6%,"$419,614,312",89.4%,2020.csv,2020
1,2,The Eight Hundred,"$461,421,559","$372,755",<0.1%,"$461,048,804",99.9%,2020.csv,2020
2,3,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%,2020.csv,2020
3,4,"My People, My Homeland","$422,390,820",-,-,"$422,390,820",100%,2020.csv,2020
4,5,Tenet,"$365,304,105","$58,504,105",16%,"$306,800,000",84%,2020.csv,2020
...,...,...,...,...,...,...,...,...,...
1195,196,Grace,"$10,048,372","$132,311",1.3%,"$9,916,061",98.7%,2025.csv,2025
1196,197,Sisu: Road to Revenge,"$9,811,703","$4,544,481",46.3%,"$5,267,222",53.7%,2025.csv,2025
1197,198,Chasse gardée 2,"$9,788,446",-,-,"$9,788,446",100%,2025.csv,2025
1198,199,Detective Kien: The Headless Horror,"$9,768,694",-,-,"$9,768,694",100%,2025.csv,2025
1199,200,Is This Thing On?,"$9,746,540","$6,185,385",63.5%,"$3,561,155",36.5%,2025.csv,2025

In [8]:
df["Domestic %"] = df['%']
df["Foreign %"] = df['%.1'] 
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year,Domestic %,Foreign %
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008",Domestic %,"$419,614,312",Foreign %,2020.csv,2020,Domestic %,Foreign %
1,2,The Eight Hundred,"$461,421,559","$372,755",Domestic %,"$461,048,804",Foreign %,2020.csv,2020,Domestic %,Foreign %
2,3,Bad Boys for Life,"$426,505,244","$206,305,244",Domestic %,"$220,200,000",Foreign %,2020.csv,2020,Domestic %,Foreign %
3,4,"My People, My Homeland","$422,390,820",-,Domestic %,"$422,390,820",Foreign %,2020.csv,2020,Domestic %,Foreign %
4,5,Tenet,"$365,304,105","$58,504,105",Domestic %,"$306,800,000",Foreign %,2020.csv,2020,Domestic %,Foreign %

In [12]:
# Deleting columns 
# new_def = df.drop(columns=['%', '%.1'])   delete and set old df to the new one
df.drop(['%', '%.1'], axis=1, inplace=True) # delete completely from the old one
df.head()

,Rank,Release Group,Worldwide,Domestic,Foreign,filename,year,Domestic %,Foreign %
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"$469,119,320","$49,505,008","$419,614,312",2020.csv,2020,Domestic %,Foreign %
1,2,The Eight Hundred,"$461,421,559","$372,755","$461,048,804",2020.csv,2020,Domestic %,Foreign %
2,3,Bad Boys for Life,"$426,505,244","$206,305,244","$220,200,000",2020.csv,2020,Domestic %,Foreign %
3,4,"My People, My Homeland","$422,390,820",-,"$422,390,820",2020.csv,2020,Domestic %,Foreign %
4,5,Tenet,"$365,304,105","$58,504,105","$306,800,000",2020.csv,2020,Domestic %,Foreign %

In [14]:

to_clean_cols = ['Worldwide', 'Domestic', 'Foreign']
                 
def currency_str_to_int(current_val):
    currency_val = current_val.replace("$", "").replace(",", "")
    try:
        currency_val = int(currency_val)
    except :
        # Takes any row value with "-" and turns into 0
        currency_val = 0
    return currency_val
        
def clean_col(row):
    """
    axis means we pass row by row 
    row = Pandas Series
    dataframe = collection of Pandas Series
    """
    #print(row)
    for col in to_clean_cols:
        current_val = row[col]
        row[col] = currency_str_to_int(current_val)
    return row
df_cleaned = df.apply(clean_col, axis=1)
df_cleaned.head()

,Rank,Release Group,Worldwide,Domestic,Foreign,filename,year,Domestic %,Foreign %
0,1,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,469119320,49505008,419614312,2020.csv,2020,Domestic %,Foreign %
1,2,The Eight Hundred,461421559,372755,461048804,2020.csv,2020,Domestic %,Foreign %
2,3,Bad Boys for Life,426505244,206305244,220200000,2020.csv,2020,Domestic %,Foreign %
3,4,"My People, My Homeland",422390820,0,422390820,2020.csv,2020,Domestic %,Foreign %
4,5,Tenet,365304105,58504105,306800000,2020.csv,2020,Domestic %,Foreign %

In [17]:
df.dtypes, df_cleaned.dtypes

(Rank             int64
 Release Group      str
 Worldwide          str
 Domestic           str
 Foreign            str
 filename           str
 year             int64
 Domestic %         str
 Foreign %          str
 dtype: object,
 Rank             int64
 Release Group      str
 Worldwide        int64
 Domestic         int64
 Foreign          int64
 filename           str
 year             int64
 Domestic %         str
 Foreign %          str
 dtype: object)

In [19]:
df_cleaned.sort_values(by=['Worldwide'], inplace=True, ascending=False)
df_cleaned.head()

,Rank,Release Group,Worldwide,Domestic,Foreign,filename,year,Domestic %,Foreign %
600,1,Avatar: The Way of Water,2320631329,684075767,1636555562,2022.csv,2022,Domestic %,Foreign %
1000,1,Ne Zha 2,2260176370,23308176,2236868194,2025.csv,2025,Domestic %,Foreign %
200,1,Spider-Man: No Way Home,1910982770,804793477,1106189293,2021.csv,2021,Domestic %,Foreign %
1001,2,Zootopia 2,1866361674,427843884,1438517790,2025.csv,2025,Domestic %,Foreign %
1200,1,Inside Out 2,1698863816,652980194,1045883622,2024.csv,2024,Domestic %,Foreign %

In [20]:
df_cleaned.reset_index(inplace=True, drop=True)
df_cleaned.head()

,Rank,Release Group,Worldwide,Domestic,Foreign,filename,year,Domestic %,Foreign %
0,1,Avatar: The Way of Water,2320631329,684075767,1636555562,2022.csv,2022,Domestic %,Foreign %
1,1,Ne Zha 2,2260176370,23308176,2236868194,2025.csv,2025,Domestic %,Foreign %
2,1,Spider-Man: No Way Home,1910982770,804793477,1106189293,2021.csv,2021,Domestic %,Foreign %
3,2,Zootopia 2,1866361674,427843884,1438517790,2025.csv,2025,Domestic %,Foreign %
4,1,Inside Out 2,1698863816,652980194,1045883622,2024.csv,2024,Domestic %,Foreign %

In [30]:
# Sorting Rank using indices
df_cleaned['Rank'] = df_cleaned.index + 1
df_cleaned.head()

,Rank,Release Group,Worldwide,Domestic,Foreign,filename,year,Domestic %,Foreign %
0,1,Avatar: The Way of Water,2320631329,684075767,1636555562,2022.csv,2022,0.294780,0.705220
1,2,Ne Zha 2,2260176370,23308176,2236868194,2025.csv,2025,0.010313,0.989687
2,3,Spider-Man: No Way Home,1910982770,804793477,1106189293,2021.csv,2021,0.421141,0.578859
3,4,Zootopia 2,1866361674,427843884,1438517790,2025.csv,2025,0.229240,0.770760
4,5,Inside Out 2,1698863816,652980194,1045883622,2024.csv,2024,0.384363,0.615637

In [31]:
df_cleaned['Domestic %'] = df_cleaned['Domestic'] / df_cleaned['Worldwide']
df_cleaned['Foreign %'] = df_cleaned['Foreign'] / df_cleaned['Worldwide']
df_cleaned.head(n=10)

,Rank,Release Group,Worldwide,Domestic,Foreign,filename,year,Domestic %,Foreign %
0,1,Avatar: The Way of Water,2320631329,684075767,1636555562,2022.csv,2022,0.294780,0.705220
1,2,Ne Zha 2,2260176370,23308176,2236868194,2025.csv,2025,0.010313,0.989687
2,3,Spider-Man: No Way Home,1910982770,804793477,1106189293,2021.csv,2021,0.421141,0.578859
3,4,Zootopia 2,1866361674,427843884,1438517790,2025.csv,2025,0.229240,0.770760
4,5,Inside Out 2,1698863816,652980194,1045883622,2024.csv,2024,0.384363,0.615637
5,6,Top Gun: Maverick,1495696292,718732821,776963471,2022.csv,2022,0.480534,0.519466
6,7,Avatar: Fire and Ash,1485065497,403405617,1081659880,2025.csv,2025,0.271642,0.728358
7,8,Barbie,1447138421,636238421,810900000,2023.csv,2023,0.439653,0.560347
8,9,The Super Mario Bros. Movie,1360879735,574934330,785945405,2023.csv,2023,0.422473,0.577527
9,10,Deadpool & Wolverine,1338073645,636745858,701327787,2024.csv,2024,0.475868,0.524132

In [32]:
df_cleaned.to_csv(output_file, index=True)